### ISSUE TITLE
Improve tests for GoogleHost class

### ISSUE THREAD

**Issue by giovannifs** [giovannifs/cloudsim#6]
As per title.

**Comment by alessandroliafook** [comment]
Improved tests considering free capacity of a host with less than 1 mips in method "IsSuitableFor()". Also included in tests of the method "nextVmForPreempting()" cases where the host is empty, and the case where all vms are destroyed.

**Comment by alessandroliafook** [comment]
Finishing issue with commits:
https://github.com/giovannifs/cloudsim/commit/b9b02a3c76b155adcbcdaa52ea8fd7119d231eaf
and 
https://github.com/giovannifs/cloudsim/commit/10a2ea947489cc8f57de5badedbcd1692f690c4d

**Comment by alessandroliafook** [comment]
Improve tests for consider decimal accuracy of 15 in methods of the GoogleHost class
