### ISSUE TITLE
Improve tests for PreemptableVmAllocationPolicy class

### ISSUE THREAD

**Issue by giovannifs** [giovannifs/cloudsim#7]
As per title.

**Comment by alessandroliafook** [comment]
Solve with commits https://github.com/giovannifs/cloudsim/commit/10a2ea947489cc8f57de5badedbcd1692f690c4d, https://github.com/giovannifs/cloudsim/commit/7efae95c2c7a156e721ec03b741e767668eb6c1a, https://github.com/giovannifs/cloudsim/commit/ecc1fa4bad8d4c8898f000e143745970dfab48cf and https://github.com/giovannifs/cloudsim/commit/1234de614496b4b4fd558bea0bf4de8122ebd1ce.
