### ISSUE TITLE
Consider more host then the first on host selection policy

### ISSUE THREAD

**Issue by alessandroliafook** [giovannifs/cloudsim#9]
Actualy the selection policy of the host that will receive the vm is make get the first host of a sorted set. The orderer of the hosts are done by available mips, not considering priority level of the vm's already alocated. Because of that, can be exists a host that has free mips to fit a vm considering the preemption, but is not the first of the sorted list.

**Comment by giovannifs** [comment]
We develped the wort fit correctly, based on the priority of the VM that is arriving.
